<a href="https://colab.research.google.com/github/kmkarakaya/ML_tutorials/blob/master/Multi_Label_Model_Evaulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[SciKit Learn: 
Model evaluation: quantifying the quality of predictions](https://lijiancheng0614.github.io/scikit-learn/modules/model_evaluation.html)



In [0]:
%matplotlib inline

#Synthetic Data:
[Calculate mean Average Precision (mAP) for multi-label classification](https://medium.com/@hfdtsinghua/calculate-mean-average-precision-map-for-multi-label-classification-b082679d31be)

First assume that in the data set we have only 3 samples as below. Each sample has 4 classes: A, B, C, and D. 
In samples more than one classes exist! Therefore, the problem multi-label classification!

After some training, some ML model produce the predicted scores.

![Sample Data with scores](https://github.com/kmkarakaya/ML_tutorials/blob/master/images/sample%20mutli%20label%20classification%20scores.png?raw=true)


In [0]:
import numpy as np
y_true = np.array([[0, 1, 1, 1],[0,0,1,0],[1,1,0,0]])
y_scores = np.array([[0.2, 0.6, 0.1, 0.8],[0.4,0.9,0.8,0.6],[0.8,0.4,0.5,0.7]])


#Threshold: Let's assume we are using **0.5 as the threshold** for prediction


In [0]:
threshold = 0.5


In [40]:
y_pred=[]
for sample in  y_scores:
  y_pred.append([1 if i>=0.5 else 0 for i in sample ] )
y_pred = np.array(y_pred)
y_pred

array([[0, 1, 0, 1],
       [0, 1, 1, 1],
       [1, 0, 1, 1]])

# [Accuracy score](http://lijiancheng0614.github.io/scikit-learn/modules/model_evaluation.html#accuracy-score)

The accuracy_score function computes the accuracy, either the fraction (default) or the count (normalize=False) of correct predictions.

**In multilabel classification**, the function returns the subset accuracy. If the entire set of predicted labels for a sample strictly match with the true set of labels, then the subset accuracy is 1.0; otherwise it is **0.0**.


In [16]:
from sklearn.metrics import accuracy_score
accuracy_score(y_true, y_pred)

0.0

**Notice**: Here, accuracy is based on if all the 4-class prediction is correct or naot.

It is not label-based!

Therefore accuracy is zero!

We have to use better metrics for multilabel classification

# [Confusion matrix](http://lijiancheng0614.github.io/scikit-learn/modules/model_evaluation.html#confusion-matrix) 

The confusion_matrix function evaluates classification accuracy by computing the confusion matrix.

By definition, entry i, j in a confusion matrix is the number of observations actually in group i, but predicted to be in group j. 

![Sample Confusion Matrix](https://github.com/kmkarakaya/ML_tutorials/blob/master/images/confusion%20matrix%20sample.png?raw=true)


In [0]:
from sklearn.metrics import confusion_matrix
#confusion_matrix(y_true, y_pred)

#[Multilabel confusion matrix](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.multilabel_confusion_matrix.html?highlight=multilabel#sklearn-metrics-multilabel-confusion-matrix)


* Compute a confusion matrix for each class or sample 
* **NOTICE:** The cells has different meaning from Binary Class Confusion Matrix! 

![MCM](https://github.com/kmkarakaya/ML_tutorials/blob/master/images/MCM%20confusion%20matrix%20sample.png?raw=true)

In [18]:
print("Actual \n", y_true)
print("\nPredicted \n",y_pred)


Actual 
 [[0 1 1 1]
 [0 0 1 0]
 [1 1 0 0]]

Predicted 
 [[0 1 0 1]
 [0 1 1 1]
 [1 0 1 1]]


In [19]:
from sklearn.metrics import multilabel_confusion_matrix
multilabel_confusion_matrix(y_true, y_pred)

array([[[2, 0],
        [0, 1]],

       [[0, 1],
        [1, 1]],

       [[0, 1],
        [1, 1]],

       [[0, 2],
        [0, 1]]])

#[Classification report](http://lijiancheng0614.github.io/scikit-learn/modules/model_evaluation.html#classification-report)

In [20]:
from sklearn.metrics import classification_report

label_names = ['label A', 'label B', 'label C', 'label D']

print(classification_report(y_true, y_pred,target_names=label_names))

              precision    recall  f1-score   support

     label A       1.00      1.00      1.00         1
     label B       0.50      0.50      0.50         2
     label C       0.50      0.50      0.50         2
     label D       0.33      1.00      0.50         1

   micro avg       0.50      0.67      0.57         6
   macro avg       0.58      0.75      0.62         6
weighted avg       0.56      0.67      0.58         6
 samples avg       0.56      0.72      0.57         6



#[Precision, recall and F-measures](http://lijiancheng0614.github.io/scikit-learn/modules/model_evaluation.html#precision-recall-and-f-measures)


Intuitively, precision is the ability of the classifier not to label as positive a sample that is negative, and recall is the ability of the classifier to find all the positive samples.

The F-measure can be interpreted as a weighted harmonic mean of the precision and recall:  reaches its best value at 1 and its worst score at 0.

Several functions allow you to analyze the precision, recall and F-measures score.

#[Precision, recall and F-measures @ Multilabel classification ](http://lijiancheng0614.github.io/scikit-learn/modules/model_evaluation.html#multiclass-and-multilabel-classification)


* In multiclass and multilabel classification task, the notions of precision, 
recall, and F-measures can be applied to each label independently. 

* There are a few ways to combine results across labels, specified by the ***average*** argument to the average_precision_score (multilabel only), f1_score, fbeta_score, precision_recall_fscore_support, precision_score and recall_score functions, as described above. 

* Note that for ***“micro”***-averaging in a multiclass setting with all labels included will produce equal precision, recall and F, while ***“weighted”*** averaging may produce an F-score that is not between precision and recall.

##Precision
[precision_score](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.precision_score.html#sklearn-metrics-precision-score)


* The precision is the ratio **tp / (tp + fp)** where tp is the number of true positives and fp the number of false positives. The precision is intuitively the ability of the classifier not to label as positive a sample that is negative.

* The best value is 1 and the worst value is 0.


***average*** parameter is required for multiclass/multilabel targets. 

* **None**, the scores for each class are returned. Otherwise, this determines the type of averaging performed on the data:

* '**micro**':
Calculate metrics globally by counting the total true positives, false negatives and false positives.

* '**macro**':
Calculate metrics for each label, and find their unweighted mean. This does not take label imbalance into account.

* '**weighted**':
Calculate metrics for each label, and find their average weighted by support (the number of true instances for each label). This alters ‘macro’ to account for label imbalance; it can result in an F-score that is not between precision and recall.

* '**samples**':
Calculate metrics for each instance, and find their average (only meaningful for multilabel classification where this differs from accuracy_score).


In [21]:
print("Actual \n", y_true)
print("\nPredicted \n",y_pred)

Actual 
 [[0 1 1 1]
 [0 0 1 0]
 [1 1 0 0]]

Predicted 
 [[0 1 0 1]
 [0 1 1 1]
 [1 0 1 1]]


####Precision of each label

In [22]:
from sklearn import metrics
print("None ", metrics.precision_score(y_true, y_pred, average=None))  


None  [1.         0.5        0.5        0.33333333]


###Average Precision
[precision_score funtion has](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.precision_score.html#sklearn-metrics-precision-score)

***average*** parameter is required for multiclass/multilabel targets. 

* **None**, the scores for each class are returned. Otherwise, this determines the type of averaging performed on the data:

* '**micro**':
Calculate metrics globally by counting the total true positives, false negatives and false positives.

* '**macro**':
Calculate metrics for each label, and find their unweighted mean. This does not take label imbalance into account.

* '**weighted**':
Calculate metrics for each label, and find their average weighted by support (the number of true instances for each label). This alters ‘macro’ to account for label imbalance; it can result in an F-score that is not between precision and recall.

* '**samples**':
Calculate metrics for each instance, and find their average (only meaningful for multilabel classification where this differs from accuracy_score).

#### Use precision_score function

In [23]:

print("micro: {:.2f}".format(metrics.precision_score(y_true, y_pred, average='micro')))
print("macro: {:.2f} ".format( metrics.precision_score(y_true, y_pred, average='macro')))
print("weighted: {:.2f} ".format( metrics.precision_score(y_true, y_pred, average='weighted')))
print("samples: {:.2f} ".format( metrics.precision_score(y_true, y_pred, average='samples')))  




micro: 0.50
macro: 0.58 
weighted: 0.56 
samples: 0.56 


####  [Use average_precision_score function](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.average_precision_score.html#sklearn-metrics-average-precision-score)

* average_precision_score(y_true, **y_score** , average='macro', sample_weight=None)

*Compute average precision (AP) from prediction scores

* average_precision_score summarizes a **precision-recall curve** as the weighted mean of precisions achieved **at each threshold**, with the increase in recall from the previous threshold used as the weight:

>>$\text{AP} = \sum_n (R_n - R_{n-1}) P_n$
 
where  and  are the precision and recall at the nth threshold [1]. 
* This implementation is not interpolated and is different from computing the area under the precision-recall curve with the trapezoidal rule, which uses linear interpolation and can be too optimistic.

* Note: this implementation is restricted to the binary classification task or **multilabel** classification task.

**IMPORTANT:** 
* Precision refers to precision at a **particular decision threshold**. For example, if you count any model output less than 0.5 as negative, and greater than 0.5 as positive. 
* But sometimes (especially if your classes are not balanced, or if you want to favor precision over recall or vice versa), you may want to **vary this threshold**. **average_precision_score function** gives you ***average precision at all such possible thresholds***, which is also similar to the ***area under the precision-recall curve***. 
* It is a useful metric to compare how well models are ordering the predictions, without considering any specific decision threshold.


In [24]:
y_scores

array([[0.2, 0.6, 0.1, 0.8],
       [0.4, 0.9, 0.8, 0.6],
       [0.8, 0.4, 0.5, 0.7]])

In [25]:
print("micro: {:.2f}".format(metrics.average_precision_score(y_true, y_scores, average='micro')))
print("macro: {:.2f} ".format( metrics.average_precision_score(y_true, y_scores, average='macro')))
print("weighted: {:.2f} ".format( metrics.average_precision_score(y_true, y_scores, average='weighted')))
print("samples: {:.2f} ".format( metrics.average_precision_score(y_true, y_scores, average='samples')))  

micro: 0.64
macro: 0.85 
weighted: 0.81 
samples: 0.72 


#### Calculate micro Precision 
* Calculate metrics **globally** by counting the total true positives and false positives.

The precision is the ratio tp / (tp + fp) 


##### Count by yourself

In [26]:
np.concatenate((y_true.reshape(12,1), y_pred.reshape(12,1)), axis=1)

array([[0, 0],
       [1, 1],
       [1, 0],
       [1, 1],
       [0, 0],
       [0, 1],
       [1, 1],
       [0, 1],
       [1, 1],
       [1, 0],
       [0, 1],
       [0, 1]])

In [27]:
TP=((y_true * y_pred) == 1).sum()
print("TP: ", TP)

TP:  4


In [28]:
converted_y_true= np.copy(y_true)
converted_y_true[converted_y_true==1] = 5
converted_y_true[converted_y_true==0] = 1
converted_y_true[converted_y_true==5] = 0
FP= ((converted_y_true * y_pred)== 1).sum()
print("FP: ", FP)

FP:  4


In [29]:
print(" Micro Precision {:.2f}".format(TP/(TP+FP)))

 Micro Precision 0.50


##### Flatten & use as in binary classification

In [30]:
print("Micro Precision: {:.2f}".format(metrics.precision_score(y_true.ravel(), y_pred.ravel())))

Micro Precision: 0.50


#### Calculate macro Precision 
* Calculate metrics for each label, and find their unweighted mean. This does not take label imbalance into account.

The precision is the ratio tp / (tp + fp) 

In [31]:
totalPrecision= 0
for i in range (len(label_names)):
  p= metrics.precision_score(y_true[:,i], y_pred[:,i])
  totalPrecision+= p
  print("For {} precision: {:.2f}".format(label_names[i], p))
print("Macro Precision: {:.2f}".format(totalPrecision/len(label_names)))

For label A precision: 1.00
For label B precision: 0.50
For label C precision: 0.50
For label D precision: 0.33
Macro Precision: 0.58


#### Calculate weighted Precision 
*  Calculate metrics for each label, and find their average **weighted by support** (the number of true instances for each label). 
*  This alters ‘macro’ to account for label **imbalance**; it can result in an *F-score that is not between precision and recall*.

The precision is the ratio tp / (tp + fp) 



In [32]:
totalPrecision=0
totalSupport=0
for i in range (len(label_names)):
  p= metrics.precision_score(y_true[:,i], y_pred[:,i])
  support= (y_true[:,i]==1).sum()
  totalSupport+=support
  totalPrecision+= p*support
  print("For {} precision: {:.2f} support: {}".format(label_names[i], p, support ))
print("Weighted Precision: {:.2f}".format(totalPrecision/totalSupport))





For label A precision: 1.00 support: 1
For label B precision: 0.50 support: 2
For label C precision: 0.50 support: 2
For label D precision: 0.33 support: 1
Weighted Precision: 0.56


#### Calculate samples Precision 

* Calculate metrics for each instance, and find their average (only meaningful for multilabel classification where this differs from accuracy_score).

##Recall
[recall_score](http://lijiancheng0614.github.io/scikit-learn/modules/generated/sklearn.metrics.recall_score.html#sklearn-metrics-recall-score)


* Compute the recall: The recall is the ratio **tp / (tp + fn)** where tp is the number of true positives and fn the number of false negatives. The recall is intuitively the ability of the classifier to find all the positive samples.

* The best value is 1 and the worst value is 0.


***average*** parameter is required for multiclass/multilabel targets. 

* **None**, the scores for each class are returned. Otherwise, this determines the type of averaging performed on the data:

* '**micro**':
Calculate metrics globally by counting the total true positives, false negatives and false positives.

* '**macro**':
Calculate metrics for each label, and find their unweighted mean. This does not take label imbalance into account.

* '**weighted**':
Calculate metrics for each label, and find their average weighted by support (the number of true instances for each label). This alters ‘macro’ to account for label imbalance; it can result in an F-score that is not between precision and recall.

* '**samples**':
Calculate metrics for each instance, and find their average (only meaningful for multilabel classification where this differs from accuracy_score).

### Recall of each label

In [33]:
print("Recall of each label: {}".format(metrics.recall_score(y_true, y_pred, average=None)))

Recall of each label: [1.  0.5 0.5 1. ]


### Average Recall

In [34]:
print("micro: {:.2f}".format(metrics.recall_score(y_true, y_pred, average='micro')))
print("macro: {:.2f} ".format( metrics.recall_score(y_true, y_pred, average='macro')))
print("weighted: {:.2f} ".format( metrics.recall_score(y_true, y_pred, average='weighted')))
print("samples: {:.2f} ".format( metrics.recall_score(y_true, y_pred, average='samples')))  

micro: 0.67
macro: 0.75 
weighted: 0.67 
samples: 0.72 


##F1 score
[f1_score](http://lijiancheng0614.github.io/scikit-learn/modules/generated/sklearn.metrics.f1_score.html#sklearn.metrics.f1_score)


* Compute the F1 score, also known as balanced F-score or F-measure

* The F1 score can be interpreted as a ***weighted average of the precision and recall***, where an F1 score reaches its best value at 1 and worst score at 0. 

* The relative contribution of precision and recall to the F1 score are equal. The formula for the F1 score is:

> >>`F1 = 2 * (precision * recall) / (precision + recall)`


In the multi-class and **multi-label** case, this is the** weighted average of the F1 score of each class**.


***average*** parameter is required for multiclass/multilabel targets. 

* **None**, the scores for each class are returned. Otherwise, this determines the type of averaging performed on the data:

* '**micro**':
Calculate metrics globally by counting the total true positives, false negatives and false positives.

* '**macro**':
Calculate metrics for each label, and find their unweighted mean. This does not take label imbalance into account.

* '**weighted**':
Calculate metrics for each label, and find their average weighted by support (the number of true instances for each label). This alters ‘macro’ to account for label imbalance; it can result in an F-score that is not between precision and recall.

### F1 of each label

In [35]:
print("F1 of each label: {}".format(metrics.f1_score(y_true, y_pred, average=None)))

F1 of each label: [1.  0.5 0.5 0.5]


### Average F1

In [36]:
print("micro: {:.2f}".format(metrics.f1_score(y_true, y_pred, average='micro')))
print("macro: {:.2f} ".format( metrics.f1_score(y_true, y_pred, average='macro')))
print("weighted: {:.2f} ".format( metrics.f1_score(y_true, y_pred, average='weighted')))
print("samples: {:.2f} ".format( metrics.f1_score(y_true, y_pred, average='samples')))  

micro: 0.57
macro: 0.62 
weighted: 0.58 
samples: 0.57 


## Summary

* **Remember**: We assumed that we are using **0.5 as the threshold** for prediction during all the computations above.

* What hapens if we select **different** values as the threshold?

Let's see!

In [43]:
print("y_true: \n{}".format(y_true))
print("y_scores: \n{}".format(y_scores))

y_true: 
[[0 1 1 1]
 [0 0 1 0]
 [1 1 0 0]]
y_scores: 
[[0.2 0.6 0.1 0.8]
 [0.4 0.9 0.8 0.6]
 [0.8 0.4 0.5 0.7]]


In [0]:
def predictLabelForGivenThreshold(threshold):
  y_pred=[]
  for sample in  y_scores:
    y_pred.append([1 if i>=threshold else 0 for i in sample ] )
  return np.array(y_pred)
  

### Classification Report when threshold = 0.5

In [53]:
y_pred  = predictLabelForGivenThreshold(0.5)
print(classification_report(y_true, y_pred,target_names=label_names))

              precision    recall  f1-score   support

     label A       1.00      1.00      1.00         1
     label B       0.50      0.50      0.50         2
     label C       0.50      0.50      0.50         2
     label D       0.33      1.00      0.50         1

   micro avg       0.50      0.67      0.57         6
   macro avg       0.58      0.75      0.62         6
weighted avg       0.56      0.67      0.58         6
 samples avg       0.56      0.72      0.57         6



### Classification Report when threshold = 0.2

In [56]:
y_pred  = predictLabelForGivenThreshold(0.2)
print(classification_report(y_true, y_pred,target_names=label_names))

              precision    recall  f1-score   support

     label A       0.33      1.00      0.50         1
     label B       0.67      1.00      0.80         2
     label C       0.50      0.50      0.50         2
     label D       0.33      1.00      0.50         1

   micro avg       0.45      0.83      0.59         6
   macro avg       0.46      0.88      0.57         6
weighted avg       0.50      0.83      0.60         6
 samples avg       0.47      0.89      0.58         6



### Classification Report when threshold = 0.8

In [55]:
y_pred  = predictLabelForGivenThreshold(0.8)
print(classification_report(y_true, y_pred,target_names=label_names))

              precision    recall  f1-score   support

     label A       1.00      1.00      1.00         1
     label B       0.00      0.00      0.00         2
     label C       1.00      0.50      0.67         2
     label D       1.00      1.00      1.00         1

   micro avg       0.75      0.50      0.60         6
   macro avg       0.75      0.62      0.67         6
weighted avg       0.67      0.50      0.56         6
 samples avg       0.83      0.61      0.61         6



### Which threshold?

* Which threshold yileds better result?
* Which metric do you care?
* How can you compare different models' success/performance?
* Which precision/recall/f1 value to report?

In [37]:
from sklearn.metrics import 

precision, recall, thresholds = precision_recall_curve(
    y_true, y_scores)
print(precision)
print(recall)
print(thresholds)

SyntaxError: ignored

# Precision-Recall Curve


Example of Precision-Recall metric to evaluate classifier output quality.

Precision-Recall is a useful measure of success of prediction when the
classes are very imbalanced. In information retrieval, precision is a
measure of result relevancy, while recall is a measure of how many truly
relevant results are returned.

The precision-recall curve shows the tradeoff between precision and
recall for different threshold. A high area under the curve represents
both high recall and high precision, where high precision relates to a
low false positive rate, and high recall relates to a low false negative
rate. High scores for both show that the classifier is returning accurate
results (high precision), as well as returning a majority of all positive
results (high recall).

A system with high recall but low precision returns many results, but most of
its predicted labels are incorrect when compared to the training labels. A
system with high precision but low recall is just the opposite, returning very
few results, but most of its predicted labels are correct when compared to the
training labels. An ideal system with high precision and high recall will
return many results, with all results labeled correctly.

Precision ($P$) is defined as the number of true positives ($T_p$)
over the number of true positives plus the number of false positives
($F_p$).

$P = \frac{T_p}{T_p+F_p}$

Recall ($R$) is defined as the number of true positives ($T_p$)
over the number of true positives plus the number of false negatives
($F_n$).

$R = \frac{T_p}{T_p + F_n}$

These quantities are also related to the ($F_1$) score, which is defined
as the harmonic mean of precision and recall.

$F1 = 2\frac{P \times R}{P+R}$

Note that the precision may not decrease with recall. The
definition of precision ($\frac{T_p}{T_p + F_p}$) shows that lowering
the threshold of a classifier may increase the denominator, by increasing the
number of results returned. If the threshold was previously set too high, the
new results may all be true positives, which will increase precision. If the
previous threshold was about right or too low, further lowering the threshold
will introduce false positives, decreasing precision.

Recall is defined as $\frac{T_p}{T_p+F_n}$, where $T_p+F_n$ does
not depend on the classifier threshold. This means that lowering the classifier
threshold may increase recall, by increasing the number of true positive
results. It is also possible that lowering the threshold may leave recall
unchanged, while the precision fluctuates.

The relationship between recall and precision can be observed in the
stairstep area of the plot - at the edges of these steps a small change
in the threshold considerably reduces precision, with only a minor gain in
recall.

**Average precision** (AP) summarizes such a plot as the weighted mean of
precisions achieved at each threshold, with the increase in recall from the
previous threshold used as the weight:

$\text{AP} = \sum_n (R_n - R_{n-1}) P_n$

where $P_n$ and $R_n$ are the precision and recall at the
nth threshold. A pair $(R_k, P_k)$ is referred to as an
*operating point*.

AP and the trapezoidal area under the operating points
(:func:`sklearn.metrics.auc`) are common ways to summarize a precision-recall
curve that lead to different results. Read more in the
`User Guide <precision_recall_f_measure_metrics>`.

Precision-recall curves are typically used in binary classification to study
the output of a classifier. In order to extend the precision-recall curve and
average precision to multi-class or multi-label classification, it is necessary
to binarize the output. One curve can be drawn per label, but one can also draw
a precision-recall curve by considering each element of the label indicator
matrix as a binary prediction (micro-averaging).

<div class="alert alert-info"><h4>Note</h4><p>See also :func:`sklearn.metrics.average_precision_score`,
             :func:`sklearn.metrics.recall_score`,
             :func:`sklearn.metrics.precision_score`,
             :func:`sklearn.metrics.f1_score`</p></div>


In binary classification settings
--------------------------------------------------------

Create simple data
..................

Try to differentiate the two first classes of the iris data



In [0]:
from sklearn import svm, datasets
from sklearn.model_selection import train_test_split
import numpy as np

iris = datasets.load_iris()
X = iris.data
y = iris.target



In [0]:
X.shape



In [0]:
# Add noisy features
random_state = np.random.RandomState(0)
n_samples, n_features = X.shape

random_features= random_state.randn(n_samples, 200 * n_features)
X = np.c_[X,random_features ]



In [0]:
X.shape


In [0]:
# Limit to the two first classes, and split into training and test
X_train, X_test, y_train, y_test = train_test_split(X[y < 2], y[y < 2],
                                                    test_size=.5,
                                                    random_state=random_state)

# Create a simple classifier
classifier = svm.LinearSVC(random_state=random_state)
classifier.fit(X_train, y_train)
y_score = classifier.decision_function(X_test)
y_predict = classifier.predict(X_test)

In [0]:
print(y_score[:5])
print(y_predict[:5])


Compute the average precision score
...................................



In [0]:
from sklearn.metrics import average_precision_score
average_precision = average_precision_score(y_test, y_score)

print('Average precision-recall score: {0:0.2f}'.format(
      average_precision))

Plot the Precision-Recall curve
................................



In [0]:
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import plot_precision_recall_curve
import matplotlib.pyplot as plt

disp = plot_precision_recall_curve(classifier, X_test, y_test)
disp.ax_.set_title('2-class Precision-Recall curve: '
                   'AP={0:0.2f}'.format(average_precision))

In multi-label settings
------------------------

Create multi-label data, fit, and predict
...........................................

We create a multi-label dataset, to illustrate the precision-recall in
multi-label settings



In [0]:
from sklearn.preprocessing import label_binarize

# Use label_binarize to be multi-label like settings
Y = label_binarize(y, classes=[0, 1, 2])
n_classes = Y.shape[1]

# Split into training and test
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=.5,
                                                    random_state=random_state)

# We use OneVsRestClassifier for multi-label prediction
from sklearn.multiclass import OneVsRestClassifier

# Run classifier
classifier = OneVsRestClassifier(svm.LinearSVC(random_state=random_state))
classifier.fit(X_train, Y_train)
y_score = classifier.decision_function(X_test)
y_predict =  classifier.predict(X_test)



In [0]:
print(y_score[:5])
print(y_predict[:5])

The average precision score in multi-label settings
....................................................



In [0]:
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import average_precision_score

# For each class
precision = dict()
recall = dict()
average_precision = dict()
for i in range(n_classes):
    precision[i], recall[i], _ = precision_recall_curve(Y_test[:, i],
                                                        y_score[:, i])
    average_precision[i] = average_precision_score(Y_test[:, i], y_score[:, i])

# A "micro-average": quantifying score on all classes jointly
precision["micro"], recall["micro"], _ = precision_recall_curve(Y_test.ravel(),
    y_score.ravel())
average_precision["micro"] = average_precision_score(Y_test, y_score,
                                                     average="micro")
print('Average precision score, micro-averaged over all classes: {0:0.2f}'
      .format(average_precision["micro"]))

### Synthetic Data


In [0]:
y_true = np.array([0, 0, 1, 1])
y_scores = np.array([0.1, 0.4, 0.35, 0.8])
precision, recall, thresholds = precision_recall_curve(
    y_true, y_scores)
print(precision)
print(recall)
print(thresholds)


In [0]:
plt.figure()

#plt.step(np.append(0.0,thresholds), np.flip(precision), where='post')
plt.step(np.append(0.0,thresholds), np.flip(recall), where='post')
plt.xlabel('Treshold')
plt.ylabel('Precision')
plt.ylim([0.0, 1.05])
plt.xlim([0.0, 1.0])
plt.title(' precision  vs threshold ')
plt.show()

In [0]:
# For each class
precision = dict()
recall = dict()
treshold = dict()
average_precision = dict()


Y_actual= np.array([[0,1,1,1], [0,0,1,0], [1,1,0,0]], dtype=np.int)
y_prediction= np.array([[0.2,0.6,0.1,0.8],[0.4,0.9,0.8,0.6],[0.8,0.4,0.5,0.7]], dtype=np.float64)

n_classes = Y_actual.shape[1]

In [0]:
for i in range(n_classes):
    precision[i], recall[i], treshold[i] = precision_recall_curve(Y_actual[:, i], y_prediction[:, i])
    average_precision[i] =average_precision_score(Y_actual[:, i], y_prediction[:, i])

print ("average_precision {} ".format(average_precision))

In [0]:
x=np.append(treshold[2],1)

print(x)
print((precision[2]))


In [0]:
plt.figure()

for i in range(n_classes):
  plt.step(np.append(treshold[i],1), precision[i], where='post')
  plt.xlabel('Treshold')
  plt.ylabel('Precision')
  plt.ylim([0.0, 1.05])
  plt.xlim([0.0, 1.0])
  plt.title(
    'Average precision score for class {}: AP={:.3f}'.format(i, average_precision[i]))
  plt.show()

In [0]:
plt.figure()

for i in range(n_classes):
  plt.step(recall[i], precision[i], where='post')
  plt.xlabel('Recall')
  plt.ylabel('Precision')
  plt.ylim([0.0, 1.05])
  plt.xlim([0.0, 1.0])
  plt.title(
    'Average precision score for class {}: AP={:.3f}'.format(i, average_precision[i]))
  plt.show()

In [0]:



# A "micro-average": quantifying score on all classes jointly
precision["micro"], recall["micro"], _ = precision_recall_curve(Y_actual.ravel(),
    y_prediction.ravel())
average_precision["None"] = average_precision_score(Y_actual, y_prediction, average=None)
average_precision["Void"] = average_precision_score(Y_actual, y_prediction)
average_precision["micro"] = average_precision_score(Y_actual, y_prediction, average="micro")
average_precision["macro"] = average_precision_score(Y_actual, y_prediction, average="macro")
average_precision["samples"] = average_precision_score(Y_actual, y_prediction, average="samples")
average_precision["weighted"] = average_precision_score(Y_actual, y_prediction, average="weighted")

#print('Average precision score, micro-averaged over all classes: {0:0.2f}'.format(average_precision["micro"]))
    
average_precision

In [0]:
precision

Plot the micro-averaged Precision-Recall curve
...............................................




In [0]:
plt.figure()
plt.step(recall['micro'], precision['micro'], where='post')

plt.xlabel('Recall')
plt.ylabel('Precision')
plt.ylim([0.0, 1.05])
plt.xlim([0.0, 1.0])
plt.title(
    'Average precision score, micro-averaged over all classes: AP={0:0.2f}'
    .format(average_precision["micro"]))

Plot Precision-Recall curve for each class and iso-f1 curves
.............................................................




In [0]:
np.linspace(0.01, 1)

In [0]:
from itertools import cycle
# setup plot details
colors = cycle(['navy', 'turquoise', 'darkorange', 'cornflowerblue', 'teal'])

plt.figure(figsize=(7, 8))
f_scores = np.linspace(0.2, 0.8, num=4)
lines = []
labels = []
for f_score in f_scores:
    x = np.linspace(0.01, 1)
    y = f_score * x / (2 * x - f_score)
    l, = plt.plot(x[y >= 0], y[y >= 0], color='gray', alpha=0.2)
    plt.annotate('f1={0:0.1f}'.format(f_score), xy=(0.9, y[45] + 0.02))

lines.append(l)
labels.append('iso-f1 curves')
l, = plt.plot(recall["micro"], precision["micro"], color='gold', lw=2)
lines.append(l)
labels.append('micro-average Precision-recall (area = {0:0.2f})'
              ''.format(average_precision["micro"]))

for i, color in zip(range(n_classes), colors):
    l, = plt.plot(recall[i], precision[i], color=color, lw=2)
    lines.append(l)
    labels.append('Precision-recall for class {0} (area = {1:0.2f})'
                  ''.format(i, average_precision[i]))

fig = plt.gcf()
fig.subplots_adjust(bottom=0.25)
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('Recall')
plt.ylabel('Precision')
plt.title('Extension of Precision-Recall curve to multi-class')
plt.legend(lines, labels, loc=(0, -.38), prop=dict(size=14))


plt.show()